/** Display-shaped player row used by tables and charts (distinct from API `Player` / `PlayerStats`). */
export interface PlayerStats {
  player: string;
  nation: string;
  pos: string;
  squad: string;
  comp: string;
  age: number;
  born: number;
  "Matches Played": number;
  "Avg Mins per Match": number;
  Goals: number;
  Assists: number;
  "Goals & Assists": number;
  "Non Penalty Goals": number;
  "Penalty Kicks Made": number;
  "Expected Goals": number;
  "Exp NPG": number;
  "Progressive Carries": number;
  "Progressive Passes": number;
  "Goals p 90": number;
  "Assists p 90": number;
  "Tackles attempted": number;
  "Tackles Won": number;
  "% Dribbles tackled": number;
  "Shots blocked": number;
  "Passes blocked": number;
  Interceptions: number;
  Clearances: number;
  "Errors made": number;
  "Goals Against": number;
  "Goals against p 90": number;
  Saves: number;
  "Saves %": number;
  "Clean Sheets": number;
  "% Clean sheets": number;
  "% Penalty saves": number;
  "Passes Completed": number;
  "Passes Attempted": number;
  "Pass completion %": number;
  "Progressive passes distance": number;
  "% Short pass completed": number;
  "% Medium passes completed": number;
  "% Long passes completed": number;
  "Key passes": number;
  "1/3": number;
  "Passes into penalty area": number;
  touches_def_pen: number;
  "Take ons attempted": number;
  "% Successful take-ons": number;
  "Times tackled during take-on": number;
  carries_prgc: number;
  "carries final 3rd": number;
  "carries penalty area": number;
  "Possessions lost": number;
  "Goals Scored": number;
  "Total Shots": number;
  "% Shots on target": number;
  "Shots p 90": number;
  "Goals per shot": number;
  "Goals per shot on target": number;
  "% Aerial Duels won": number;
  "Shot creating actions p 90": number;
  "Goal creating actions p 90": number;
  "Crosses Stopped": number;
  season: string;
}
