import { Player, PlayerStats } from "@/types/football";

const DEFAULT_STATS: PlayerStats = {
  player_id: "",
  matches_played: 0,
  total_minutes: 0,
  goals: 0,
  assists: 0,
  goals_assists: 0,
  non_penalty_goals: 0,
  penalty_kicks_made: 0,
  xg: 0,
  exp_npg: 0,
  progressive_carries: 0,
  progressive_passes: 0,
  goals_per_90: 0,
  assists_per_90: 0,
  tackles_attempted: 0,
  tackles_won: 0,
  dribbles_tackled_pct: 0,
  shots_blocked: 0,
  passes_blocked: 0,
  interceptions: 0,
  clearances: 0,
  errors_made: 0,
  goals_against: 0,
  goals_against_per_90: 0,
  saves: 0,
  saves_pct: 0,
  clean_sheets: 0,
  clean_sheets_pct: 0,
  penalty_saves_pct: 0,
  passes_completed: 0,
  passes_attempted: 0,
  pass_completion_pct: 0,
  prog_passes_dist: 0,
  short_pass_pct: 0,
  medium_pass_pct: 0,
  long_pass_pct: 0,
  key_passes: 0,
  passes_final_third: 0,
  passes_penalty_area: 0,
  touches_def_pen: 0,
  take_ons_attempted: 0,
  take_ons_success_pct: 0,
  take_ons_tackled: 0,
  carries_prgc: 0,
  carries_final_third: 0,
  carries_penalty_area: 0,
  possessions_lost: 0,
  goals_scored: 0,
  total_shots: 0,
  shots_on_target_pct: 0,
  shots_per_90: 0,
  goals_per_shot: 0,
  goals_per_shot_on_target: 0,
  aerial_duels_won_pct: 0,
  sca_per_90: 0,
  gca_per_90: 0,
  crosses_stopped: 0,
  season: "2023-2024",
  updated_at: new Date().toISOString(),
};

export const MOCK_PLAYERS: Player[] = [
  {
    id: "1",
    name: "Erling Haaland",
    team: "Manchester City",
    comp: "Premier League",
    age: 23,
    born: 2000,
    position: "Forward",
    nationality: "Norway",
    image_url: "https://placehold.co/400x400/0f172a/f1f5f9?text=Haaland",
    created_at: new Date().toISOString(),
    stats: {
      ...DEFAULT_STATS,
      player_id: "1",
      matches_played: 31,
      total_minutes: 2542,
      goals: 32,
      assists: 5,
      xg: 28.5,
      key_passes: 28,
      progressive_passes: 28,
      tackles_won: 2,
      pass_completion_pct: 75.4,
      progressive_carries: 45,
      total_shots: 120,
      goals_per_shot: 0.27,
      aerial_duels_won_pct: 55.2,
    },
  },
  {
    id: "2",
    name: "Kylian Mbappé",
    team: "Real Madrid",
    comp: "La Liga",
    age: 25,
    born: 1998,
    position: "Forward",
    nationality: "France",
    image_url: "https://placehold.co/400x400/0f172a/f1f5f9?text=Mbappe",
    created_at: new Date().toISOString(),
    stats: {
      ...DEFAULT_STATS,
      player_id: "2",
      matches_played: 29,
      total_minutes: 2480,
      goals: 28,
      assists: 12,
      xg: 24.2,
      key_passes: 45,
      progressive_passes: 52,
      tackles_won: 8,
      pass_completion_pct: 82.1,
      progressive_carries: 110,
      total_shots: 115,
      goals_per_shot: 0.24,
      aerial_duels_won_pct: 32.1,
    },
  },
  {
    id: "3",
    name: "Vinicius Jr",
    team: "Real Madrid",
    comp: "La Liga",
    age: 24,
    born: 2000,
    position: "Forward",
    nationality: "Brazil",
    image_url: "https://placehold.co/400x400/0f172a/f1f5f9?text=Vinicius+Jr",
    created_at: new Date().toISOString(),
    stats: {
      ...DEFAULT_STATS,
      player_id: "3",
      matches_played: 30,
      total_minutes: 2580,
      goals: 18,
      assists: 15,
      xg: 15.8,
      key_passes: 62,
      progressive_passes: 38,
      tackles_won: 12,
      pass_completion_pct: 79.8,
      progressive_carries: 165,
      total_shots: 85,
      goals_per_shot: 0.21,
      aerial_duels_won_pct: 28.5,
    },
  },
];

export const getPlayerByIdMock = (id: string): Player | undefined => {
  return MOCK_PLAYERS.find((player) => player.id === id);
};
